arm: plat-omap: counter_32k: Fix build error due to IS_ERR
Fix the following build error by including linux/err.h
arch/arm/plat-omap/counter_32k.c: In function 'omap_init_clocksource_32k':
arch/arm/plat-omap/counter_32k.c:167: error: implicit declaration of
                                      function 'IS_ERR'

The above error is due to the following commit:
subject: arm: plat-omap: counter_32k: use IS_ERR() instead of NULL check
commit: 235fbace0334c846c21e902f330020122fc85955

Created on linux-omap-2.6 branch: omap-fixes

Signed-off-by: Sourav Poddar <sourav.poddar@ti.com>
Reviewed-by: Charulatha V <charu@ti.com>
Acked-by: Felipe Balbi <balbi@ti.com>