TI816X: Removes the compilation error for other chips
This patch removes the compilation error, which are encountring
while building the kernel for other devices. Error details as follows

CC	arch/arm/mach-omap2/clock.o
CC	arch/arm/mach-omap2/clock_common_data.o
CC	arch/arm/mach-omap2/clkt_dpll.o
CC	arch/arm/mach-omap2/clkt_clksel.o
arch/arm/mach-omap2/clkt_clksel.c: In function 'ti816x_clksel_set_rate':
arch/arm/mach-omap2/clkt_clksel.c:609: error: 'struct clk' has no member named 'fapll_data'
arch/arm/mach-omap2/clkt_clksel.c:610: error: 'struct clk' has no member named 'fapll_data'
make[1]: *** [arch/arm/mach-omap2/clkt_clksel.o] Error 1
make: *** [arch/arm/mach-omap2] Error 2

Signed-off-by: Anil Kumar Ch <anilkumar@ti.com>
Signed-off-by: Sriramakrishnan A G <srk@ti.com>